### ISSUE TITLE
https://simpleiot.net/docs/install/solo

### ISSUE THREAD

**Issue by Ajb2k3** [awslabs/simpleiot#3]
The steps on this page fail at the beginning with
Digest: sha256:e2855ffec20b41aa9fc3cd93da5565f5019c1541e2a1045b8b766c66a0b10712
Status: Downloaded newer image for amazon/simpleiot-installer:latest
docker.io/amazon/simpleiot-installer:latest
0
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/adambryant/.aws.
See 'docker run --help'.

and iot cloud uninstall
just failed to run

**Comment by Ajb2k3** [comment]
Ok so fixed it by adding .aws folder but now getting this:
```
Iotcdk: creating CloudFormation changeset...
1:32:37 PM | CREATE_FAILED        | AWS::CloudFormation::Stack | timestreamNest
edSt...ckResourceF35A75C1
Template format error: Unrecognized resource types: [AWS::Timestream::Table, AW
S::Timestream::Database]


 ❌  Iotcdk failed: Error: The stack named Iotcdk failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Template format error: Unrecognized resource types: [AWS::Timestream::Table, AWS::Timestream::Database]
    at prepareAndExecuteChangeSet (/usr/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:386:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/usr/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:219:24)
    at initCommandLine (/usr/lib/node_modules/aws-cdk/lib/cli.ts:347:12)
****************************************************
*** Newer version of CDK is available [2.41.0]   ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************

The stack named Iotcdk failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Template format error: Unrecognized resource types: [AWS::Timestream::Table, AWS::Timestream::Database]
ERROR: please fix problems then re-run
0
┏━━━━━━━━━━━━━━━━┳━━━━━━━━━┓
┃ Install Status ┃ Message ┃
┡━━━━━━━━━━━━━━━━╇━━━━━━━━━┩
│ OK             │         │
└────────────────┴─────────┘

```

and iot cloud uninstall still not working

**Comment by Ajb2k3** [comment]
More issues
 CREATE_FAILED        | AWS::CloudFormation::Stack | timestreamNestedSt...ckResourceF35A75C1
Template format error: Unrecognized resource types: [AWS::Timestream::Table, AWS::Timestream::Database]
